version: '2'

volumes:
  pg_data:

services:
  scl_db:
    container_name: scl_db
    image: mdillon/postgis:11
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

  scl_api:
    container_name: scl_api
    build:
        context: .
        dockerfile: Dockerfile
    image: scl-api:latest
    volumes:
      - $PWD/src:/var/projects/webapp
    ports:
      - 8181:8181
    env_file:
      - .env

    links:
      - scl_db
