# Generated by Django 2.2.12 on 2021-03-30 22:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_auto_20210317_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
