# Generated by Django 2.2.12 on 2021-06-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_auto_20210421_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obsprofile',
            options={'verbose_name': 'observations user profile'},
        ),
    ]
