# Generated by Django 2.2.6 on 2019-12-09 19:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0002_application")]

    operations = [
        migrations.RemoveField(model_name="protectedarea", name="created_by"),
        migrations.RemoveField(model_name="protectedarea", name="updated_by"),
        migrations.AlterModelOptions(
            name="fragmentstats",
            options={
                "ordering": ("date", "country", "fragment"),
                "verbose_name": "fragment statistics",
                "verbose_name_plural": "fragment statistics",
            },
        ),
        migrations.AlterModelOptions(
            name="restorationstats",
            options={
                "ordering": ("date", "country", "restoration_landscape"),
                "verbose_name": "restoration landscape statistics",
                "verbose_name_plural": "restoration landscape statistics",
            },
        ),
        migrations.AlterModelOptions(
            name="sclstats",
            options={
                "ordering": ("date", "country", "scl"),
                "verbose_name": "SCL statistics",
                "verbose_name_plural": "SCL statistics",
            },
        ),
        migrations.AlterModelOptions(
            name="surveystats",
            options={
                "ordering": ("date", "country", "survey_landscape"),
                "verbose_name": "survey landscape statistics",
                "verbose_name_plural": "survey landscape statistics",
            },
        ),
        migrations.RemoveField(model_name="fragmentstats", name="biome"),
        migrations.RemoveField(model_name="fragmentstats", name="pa"),
        migrations.RemoveField(model_name="restorationstats", name="biome"),
        migrations.RemoveField(model_name="restorationstats", name="pa"),
        migrations.RemoveField(model_name="sclstats", name="biome"),
        migrations.RemoveField(model_name="sclstats", name="pa"),
        migrations.RemoveField(model_name="surveystats", name="biome"),
        migrations.RemoveField(model_name="surveystats", name="pa"),
        migrations.AddField(
            model_name="fragmentlandscape",
            name="areas",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restorationlandscape",
            name="areas",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scl",
            name="areas",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveylandscape",
            name="areas",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(name="Biome"),
        migrations.DeleteModel(name="ProtectedArea"),
    ]
