# Generated by Django 2.2.6 on 2019-12-15 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("api", "0004_auto_20191212_0352")]

    operations = [
        migrations.AlterModelOptions(
            name="fragmentstats",
            options={
                "ordering": ("country", "fragment__date"),
                "verbose_name": "fragment statistics",
                "verbose_name_plural": "fragment statistics",
            },
        ),
        migrations.AlterModelOptions(
            name="restorationstats",
            options={
                "ordering": ("country", "restoration_landscape__date"),
                "verbose_name": "restoration landscape statistics",
                "verbose_name_plural": "restoration landscape statistics",
            },
        ),
        migrations.AlterModelOptions(
            name="sclstats",
            options={
                "ordering": ("country", "scl__date"),
                "verbose_name": "SCL statistics",
                "verbose_name_plural": "SCL statistics",
            },
        ),
        migrations.AlterModelOptions(
            name="surveystats",
            options={
                "ordering": ("country", "survey_landscape__date"),
                "verbose_name": "survey landscape statistics",
                "verbose_name_plural": "survey landscape statistics",
            },
        ),
        migrations.RemoveField(model_name="fragmentstats", name="date"),
        migrations.RemoveField(model_name="restorationstats", name="date"),
        migrations.RemoveField(model_name="sclstats", name="date"),
        migrations.RemoveField(model_name="surveystats", name="date"),
        migrations.AddField(
            model_name="fragmentlandscape",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="restorationlandscape",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="scl",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="surveylandscape",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
