# Generated by Django 2.2.9 on 2020-03-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0006_probabilitycoefficients")]

    operations = [migrations.DeleteModel(name="ProbabilityCoefficients")]
