# Generated by Django 2.2.12 on 2021-03-16 14:02

from django.db import migrations
from django.db.migrations import RunPython


def create_default_species(apps, schema_editor):
    Genus = apps.get_model("api", "Genus")
    Species = apps.get_model("api", "Species")
    panthera, created = Genus.objects.get_or_create(name="Panthera")
    default_species_attribs = dict(
        genus=panthera,
        name="tigris",
        name_common="tiger",
        colid="9c35aba4cb7f388bf29a05fba221135c",
        iucnid=15955,
    )
    tiger, created = Species.objects.get_or_create(**default_species_attribs)


# def remove_default_species(apps, schema_editor):
#     Genus = apps.get_model("api", "Genus")
#     Species = apps.get_model("api", "Species")
#     panthera = Genus.objects.get(name="Panthera")
#     default_species_attribs = dict(
#         genus=panthera,
#         name="tigris",
#         name_common="tiger",
#         colid="9c35aba4cb7f388bf29a05fba221135c",
#         iucnid=15955,
#     )
#     tiger = Species.objects.get(**default_species_attribs)
#     tiger.delete()
#     panthera.delete()


class Migration(migrations.Migration):

    dependencies = [("api", "0007_delete_probabilitycoefficients")]

    # don't risk deleting everything!
    operations = [RunPython(create_default_species, migrations.RunPython.noop)]
