# Generated by Django 2.2.12 on 2021-06-01 14:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210316_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=749, multiple=True),
        ),
    ]
