# Generated by Django 2.2.24 on 2022-03-29 14:41

from django.db import migrations
from api.models import (
    RestorationLandscape,
    RestorationStats,
    SCL,
    SCLStats,
    SurveyLandscape,
    SurveyStats
)


def truncate(*args, **kwargs):
    RestorationLandscape.objects.all().delete()
    RestorationStats.objects.all().delete()
    SCL.objects.all().delete()
    SCLStats.objects.all().delete()
    SurveyLandscape.objects.all().delete()
    SurveyStats.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210601_1449'),
    ]

    operations = [
        migrations.RunPython(truncate, migrations.RunPython.noop)
    ]
