# Generated by Django 2.2.24 on 2022-03-29 14:41

from django.apps import apps
from django.db import migrations


def truncate(*args, **kwargs):
    RestorationLandscape = apps.get_model("api", "RestorationLandscape")
    RestorationStats = apps.get_model("api", "RestorationStats")
    SCL = apps.get_model("api", "SCL")
    SCLStats = apps.get_model("api", "SCLStats")
    SurveyLandscape = apps.get_model("api", "SurveyLandscape")
    SurveyStats = apps.get_model("api", "SurveyStats")

    RestorationLandscape.objects.all().delete()
    RestorationStats.objects.all().delete()
    SCL.objects.all().delete()
    SCLStats.objects.all().delete()
    SurveyLandscape.objects.all().delete()
    SurveyStats.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_fragment_fields'),
    ]

    operations = [
        migrations.RunPython(truncate, migrations.RunPython.noop)
    ]
