# Generated by Django 2.2.24 on 2022-04-03 18:16

from decimal import Decimal
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_truncate_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndigenousRangeCountryStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('area', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indigenousrangecountrystats_created_by', to='api.Profile')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Species')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indigenousrangecountrystats_updated_by', to='api.Profile')),
            ],
            options={
                'ordering': ('species', 'country'),
            },
        ),
    ]
