# Generated by Django 3.2.12 on 2022-08-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_indigenousrangecountrystats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restorationfragmentstats',
            options={'ordering': ('restoration_fragment__date',), 'verbose_name': 'restoration fragment statistics', 'verbose_name_plural': 'restoration fragment statistics'},
        ),
        migrations.AlterModelOptions(
            name='restorationstats',
            options={'ordering': ('restoration_landscape__date',), 'verbose_name': 'restoration landscape statistics', 'verbose_name_plural': 'restoration landscape statistics'},
        ),
        migrations.AlterModelOptions(
            name='sclstats',
            options={'ordering': ('scl__date',), 'verbose_name': 'SCL statistics', 'verbose_name_plural': 'SCL statistics'},
        ),
        migrations.AlterModelOptions(
            name='speciesfragmentstats',
            options={'ordering': ('species_fragment__date',), 'verbose_name': 'species fragment statistics', 'verbose_name_plural': 'species fragment statistics'},
        ),
        migrations.AlterModelOptions(
            name='surveyfragmentstats',
            options={'ordering': ('survey_fragment__date',), 'verbose_name': 'survey fragment statistics', 'verbose_name_plural': 'survey fragment statistics'},
        ),
        migrations.AlterModelOptions(
            name='surveystats',
            options={'ordering': ('survey_landscape__date',), 'verbose_name': 'survey landscape statistics', 'verbose_name_plural': 'survey landscape statistics'},
        ),
        migrations.AlterField(
            model_name='restorationfragmentstats',
            name='biome_areas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restorationstats',
            name='biome_areas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sclstats',
            name='biome_areas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesfragmentstats',
            name='biome_areas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyfragmentstats',
            name='biome_areas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveystats',
            name='biome_areas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField()),
                ('report', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_data',
                'unique_together': {('task_date', 'report')},
            },
        ),
    ]
