# Generated by Django 3.2.12 on 2022-08-29 21:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220825_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(blank=True, max_length=2, unique=True)),
                ('iso3', models.CharField(blank=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('isonumeric', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(blank=True, max_length=2, unique=True)),
                ('iso3', models.CharField(blank=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('isonumeric', models.IntegerField(blank=True, null=True)),
                ('gadmi_code', models.IntegerField(blank=True, null=True)),
                ('gadmi_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gadmi_type', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'states',
            },
        ),
    ]
